#!/usr/bin/env python3
"""播种扩展因子库（65 个因子，覆盖全部 7 大类：技术/估值/成长/量价/情绪/基本面/宏观/综合策略）

用法：
    cd investdojo/python-services
    python ../scripts/seed_factors_extended.py
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "python-services"))

from common.supabase_client import get_supabase_client


FACTORS = [
    # ═══ 技术面 - 趋势 ═══
    {
        "id": "ma_cross_5_20",
        "name": "5日均线金叉20日均线",
        "name_en": "MA5 cross up MA20",
        "description": "短期均线（5日）向上穿越中期均线（20日），经典短线趋势启动信号",
        "category": "technical",
        "tags": ["趋势", "短线", "经典"],
        "formula": "MA(close,5) cross_up MA(close,20)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 30,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "ma_cross_20_60",
        "name": "20日均线金叉60日均线",
        "name_en": "MA20 cross up MA60",
        "description": "中期均线向上穿越长期均线，中线趋势启动信号",
        "category": "technical",
        "tags": ["趋势", "中线", "经典"],
        "formula": "MA(close,20) cross_up MA(close,60)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 80,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "ma_bullish_alignment",
        "name": "均线多头排列",
        "name_en": "MA bullish alignment",
        "description": "MA5 > MA10 > MA20 > MA60，四条均线多头排列，强趋势确认",
        "category": "technical",
        "tags": ["趋势", "中线", "强势"],
        "formula": "MA(close,5) > MA(close,10) AND MA(close,10) > MA(close,20) AND MA(close,20) > MA(close,60)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 80,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "ema_cross_12_26",
        "name": "EMA12 金叉 EMA26",
        "name_en": "EMA12 cross up EMA26",
        "description": "指数移动平均 12 日上穿 26 日，类似 MACD 零轴判断",
        "category": "technical",
        "tags": ["趋势", "短线", "EMA"],
        "formula": "EMA(close,12) cross_up EMA(close,26)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 40,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    # ═══ 技术面 - 动量 ═══
    {
        "id": "macd_golden_cross",
        "name": "MACD 金叉",
        "name_en": "MACD golden cross",
        "description": "DIF 线向上穿越 DEA 线，经典动量启动信号",
        "category": "technical",
        "tags": ["动量", "经典", "短线"],
        "formula": "MACD_DIF cross_up MACD_DEA",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 40,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "macd_death_cross",
        "name": "MACD 死叉",
        "name_en": "MACD death cross",
        "description": "DIF 线向下穿越 DEA 线，动量衰减卖出信号",
        "category": "technical",
        "tags": ["动量", "经典", "卖出"],
        "formula": "MACD_DIF cross_down MACD_DEA",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 40,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    # ═══ 技术面 - 反转 ═══
    {
        "id": "rsi_oversold",
        "name": "RSI 超卖反弹",
        "name_en": "RSI oversold bounce",
        "description": "RSI(14) 从 30 以下向上突破 30，超卖反弹信号",
        "category": "technical",
        "tags": ["反转", "超卖", "短线"],
        "formula": "RSI(14) cross_up 30",
        "formula_type": "dsl",
        "output_type": "boolean",
        "output_range": [0, 100],
        "lookback_days": 20,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "rsi_overbought",
        "name": "RSI 超买回落",
        "name_en": "RSI overbought pullback",
        "description": "RSI(14) 从 70 以上向下跌破 70，超买回落信号",
        "category": "technical",
        "tags": ["反转", "超买", "短线"],
        "formula": "RSI(14) cross_down 70",
        "formula_type": "dsl",
        "output_type": "boolean",
        "output_range": [0, 100],
        "lookback_days": 20,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    # ═══ 技术面 - 波动 ═══
    {
        "id": "boll_break_upper",
        "name": "突破布林带上轨",
        "name_en": "Break Bollinger upper band",
        "description": "收盘价突破布林带上轨（MA20 + 2 倍标准差），强势突破信号",
        "category": "technical",
        "tags": ["波动", "突破", "布林"],
        "formula": "close > MA(close,20) + STD(close,20) * 2",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 25,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "boll_break_lower",
        "name": "跌破布林带下轨",
        "name_en": "Break Bollinger lower band",
        "description": "收盘价跌破布林带下轨（MA20 - 2 倍标准差），超跌反弹机会",
        "category": "technical",
        "tags": ["波动", "超跌", "布林"],
        "formula": "close < MA(close,20) - STD(close,20) * 2",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 25,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "price_new_high_60",
        "name": "创60日新高",
        "name_en": "60-day new high",
        "description": "收盘价创 60 日新高，突破前期高点",
        "category": "technical",
        "tags": ["突破", "强势", "中线"],
        "formula": "close >= MAX(close,60)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 65,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "price_new_low_60",
        "name": "创60日新低",
        "name_en": "60-day new low",
        "description": "收盘价创 60 日新低，弱势破位",
        "category": "technical",
        "tags": ["破位", "弱势", "风控"],
        "formula": "close <= MIN(close,60)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 65,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    # ═══ 量价面 ═══
    {
        "id": "volume_breakout_3x",
        "name": "成交量放大 3 倍",
        "name_en": "Volume 3x breakout",
        "description": "当日成交量超过 20 日均量 3 倍，且价格收阳",
        "category": "technical",
        "tags": ["量能", "突破", "短线"],
        "formula": "volume > MA(volume,20) * 3 AND close > open",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 25,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "volume_shrink_below_half",
        "name": "缩量至半数以下",
        "name_en": "Volume shrink below 50%",
        "description": "当日成交量不足 20 日均量的一半，市场观望情绪浓",
        "category": "technical",
        "tags": ["量能", "缩量", "观望"],
        "formula": "volume < MA(volume,20) * 0.5",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 25,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "volume_price_diverge_up",
        "name": "量价背离（上涨缩量）",
        "name_en": "Volume-price divergence (up)",
        "description": "价格上涨但成交量低于 20 日均量，上涨动能不足",
        "category": "technical",
        "tags": ["量价", "背离", "风险"],
        "formula": "close > MA(close,5) AND volume < MA(volume,20)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 25,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    # ═══ 估值面 ═══
    {
        "id": "pe_ttm_low",
        "name": "PE(TTM) 低估值",
        "name_en": "PE TTM undervalued",
        "description": "滚动市盈率低于 15 倍，价值投资入场信号",
        "category": "valuation",
        "tags": ["估值", "价值", "长线"],
        "formula": "pe_ttm < 15",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "pe_ttm_high",
        "name": "PE(TTM) 高估值",
        "name_en": "PE TTM overvalued",
        "description": "滚动市盈率高于 60 倍，估值泡沫风险",
        "category": "valuation",
        "tags": ["估值", "泡沫", "风控"],
        "formula": "pe_ttm > 60",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    # ═══ 成长面 ═══
    {
        "id": "revenue_high_growth",
        "name": "营收高增长",
        "name_en": "High revenue growth",
        "description": "营收同比增速超过 30%，高成长赛道",
        "category": "growth",
        "tags": ["成长", "营收", "高增长"],
        "formula": "yoy_ni > 30",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "roe_excellent",
        "name": "ROE 优秀",
        "name_en": "Excellent ROE",
        "description": "ROE 大于 15%，公司盈利能力强",
        "category": "growth",
        "tags": ["基本面", "ROE", "优质"],
        "formula": "roe > 15",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    # ═══ 情绪面 / 综合 ═══
    {
        "id": "big_red_candle",
        "name": "大阳线（涨幅>5%）",
        "name_en": "Big red candle (>5%)",
        "description": "单日涨幅超过 5% 且收盘价等于最高价附近，强势大阳线",
        "category": "technical",
        "tags": ["情绪", "强势", "短线"],
        "formula": "close > open * 1.05 AND close > high * 0.99",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    # ═══════════════════════════════════════════════════════
    # 以下为扩展因子（21-50）
    # ═══════════════════════════════════════════════════════
    # ─── 技术面 - 均线 ───
    {
        "id": "ma_cross_5_10",
        "name": "5日均线金叉10日均线",
        "name_en": "MA5 cross up MA10",
        "description": "超短线均线金叉，适合日内到 3 天的短线交易",
        "category": "technical",
        "tags": ["趋势", "超短线", "经典"],
        "formula": "MA(close,5) cross_up MA(close,10)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 15,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "ma_death_cross_5_20",
        "name": "5日均线死叉20日均线",
        "name_en": "MA5 cross down MA20",
        "description": "短期均线下穿中期均线，短线趋势结束卖出信号",
        "category": "technical",
        "tags": ["趋势", "短线", "卖出"],
        "formula": "MA(close,5) cross_down MA(close,20)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 30,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "price_above_ma60",
        "name": "站上60日均线",
        "name_en": "Price above MA60",
        "description": "收盘价站上 60 日均线，中期趋势转多",
        "category": "technical",
        "tags": ["趋势", "中线", "支撑"],
        "formula": "close > MA(close,60)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 65,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "price_below_ma60",
        "name": "跌破60日均线",
        "name_en": "Price below MA60",
        "description": "收盘价跌破 60 日均线，中期趋势转空",
        "category": "technical",
        "tags": ["趋势", "中线", "风控"],
        "formula": "close < MA(close,60)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 65,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "ma_bearish_alignment",
        "name": "均线空头排列",
        "name_en": "MA bearish alignment",
        "description": "MA5 < MA10 < MA20 < MA60，四条均线空头排列，弱势确认",
        "category": "technical",
        "tags": ["趋势", "中线", "弱势"],
        "formula": "MA(close,5) < MA(close,10) AND MA(close,10) < MA(close,20) AND MA(close,20) < MA(close,60)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 80,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    # ─── 技术面 - RSI 进阶 ───
    {
        "id": "rsi_strong_zone",
        "name": "RSI 强势区间",
        "name_en": "RSI strong zone",
        "description": "RSI(14) 在 50-70 之间，处于健康上升趋势",
        "category": "technical",
        "tags": ["动量", "强势", "趋势"],
        "formula": "RSI(14) > 50 AND RSI(14) < 70",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 20,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "rsi_extreme_oversold",
        "name": "RSI 极度超卖",
        "name_en": "RSI extreme oversold",
        "description": "RSI(14) < 20，极度超卖，恐慌性抛售可能见底",
        "category": "technical",
        "tags": ["反转", "超卖", "极端"],
        "formula": "RSI(14) < 20",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 20,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    # ─── 技术面 - 价格形态 ───
    {
        "id": "gap_up",
        "name": "跳空高开",
        "name_en": "Gap up",
        "description": "开盘价高于昨日最高价，形成向上跳空缺口",
        "category": "technical",
        "tags": ["缺口", "强势", "短线"],
        "formula": "open > preclose * 1.02",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "gap_down",
        "name": "跳空低开",
        "name_en": "Gap down",
        "description": "开盘价低于昨日最低价，形成向下跳空缺口",
        "category": "technical",
        "tags": ["缺口", "弱势", "风险"],
        "formula": "open < preclose * 0.98",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "hammer_candle",
        "name": "锤子线（下影线长）",
        "name_en": "Hammer candle",
        "description": "下影线长度超过实体 2 倍，且收盘在上半段，底部反转信号",
        "category": "technical",
        "tags": ["K线形态", "反转", "底部"],
        "formula": "close > open AND (open - low) > (close - open) * 2",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "big_green_candle",
        "name": "大阴线（跌幅>5%）",
        "name_en": "Big green candle (>5%)",
        "description": "单日跌幅超过 5%，恐慌性抛售",
        "category": "technical",
        "tags": ["情绪", "恐慌", "风控"],
        "formula": "close < open * 0.95",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "narrow_range_5",
        "name": "5日窄幅整理",
        "name_en": "5-day narrow range",
        "description": "近 5 日振幅（最高-最低）/ 收盘价 < 3%，蓄势待变",
        "category": "technical",
        "tags": ["整理", "蓄势", "突破前兆"],
        "formula": "(MAX(high,5) - MIN(low,5)) / close < 0.03",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 10,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "price_new_high_20",
        "name": "创20日新高",
        "name_en": "20-day new high",
        "description": "收盘价创 20 日新高，短线突破信号",
        "category": "technical",
        "tags": ["突破", "短线", "强势"],
        "formula": "close >= MAX(close,20)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 25,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "price_new_low_20",
        "name": "创20日新低",
        "name_en": "20-day new low",
        "description": "收盘价创 20 日新低，短线破位信号",
        "category": "technical",
        "tags": ["破位", "弱势", "风控"],
        "formula": "close <= MIN(close,20)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 25,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    # ─── 量价面 - 进阶 ───
    {
        "id": "volume_breakout_2x",
        "name": "成交量放大 2 倍",
        "name_en": "Volume 2x breakout",
        "description": "当日成交量超过 20 日均量 2 倍，温和放量",
        "category": "technical",
        "tags": ["量能", "放量", "关注"],
        "formula": "volume > MA(volume,20) * 2",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 25,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "volume_continuous_increase_3",
        "name": "连续3日放量",
        "name_en": "3-day volume increase",
        "description": "近 3 日成交量逐日递增，资金持续流入",
        "category": "technical",
        "tags": ["量能", "持续", "关注"],
        "formula": "volume > MA(volume,20) * 1.5 AND DIFF(volume,1) > 0",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 25,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "volume_price_up_together",
        "name": "量价齐升",
        "name_en": "Volume and price up together",
        "description": "价格上涨且成交量大于 20 日均量，健康上涨",
        "category": "technical",
        "tags": ["量价", "健康", "确认"],
        "formula": "close > open AND volume > MA(volume,20)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 25,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    # ─── 估值面 - 进阶 ───
    {
        "id": "pe_ttm_moderate",
        "name": "PE(TTM) 合理估值",
        "name_en": "PE TTM moderate",
        "description": "PE(TTM) 在 15-30 之间，估值合理",
        "category": "valuation",
        "tags": ["估值", "合理", "中性"],
        "formula": "pe_ttm > 15 AND pe_ttm < 30",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "low_debt_ratio",
        "name": "低负债率",
        "name_en": "Low debt ratio",
        "description": "资产负债率低于 40%，财务稳健",
        "category": "valuation",
        "tags": ["财务", "稳健", "安全"],
        "formula": "debt_asset_ratio < 40",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "high_gp_margin",
        "name": "高毛利率（>40%）",
        "name_en": "High gross margin (>40%)",
        "description": "毛利率超过 40%，具有较强的定价权或护城河",
        "category": "valuation",
        "tags": ["盈利", "护城河", "优质"],
        "formula": "gp_margin > 40",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    # ─── 成长面 - 进阶 ───
    {
        "id": "profit_high_growth",
        "name": "净利润高增长（>50%）",
        "name_en": "High profit growth (>50%)",
        "description": "归母净利润同比增速超过 50%，爆发式增长",
        "category": "growth",
        "tags": ["成长", "利润", "爆发"],
        "formula": "yoy_pni > 50",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "profit_decline",
        "name": "净利润下滑（<-20%）",
        "name_en": "Profit decline (<-20%)",
        "description": "净利润同比下滑超过 20%，业绩恶化风险",
        "category": "growth",
        "tags": ["成长", "下滑", "风险"],
        "formula": "yoy_ni < -20",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "eps_growth_positive",
        "name": "EPS 同比正增长",
        "name_en": "EPS YoY positive",
        "description": "每股收益同比增长为正，盈利改善",
        "category": "growth",
        "tags": ["成长", "EPS", "改善"],
        "formula": "yoy_eps > 0",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    # ─── 综合策略型因子 ───
    {
        "id": "value_growth_combo",
        "name": "价值成长双优",
        "name_en": "Value-growth combo",
        "description": "PE < 25 且 ROE > 12%，兼具估值和成长优势",
        "category": "custom",
        "tags": ["综合", "价值", "成长"],
        "formula": "pe_ttm < 25 AND roe > 12",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "trend_volume_confirm",
        "name": "趋势+量能确认",
        "name_en": "Trend with volume confirm",
        "description": "站上 20 日均线 + 成交量大于均量，趋势与量能共振",
        "category": "custom",
        "tags": ["综合", "趋势", "量能"],
        "formula": "close > MA(close,20) AND volume > MA(volume,20)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 25,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "golden_pit",
        "name": "黄金坑（急跌后企稳）",
        "name_en": "Golden pit",
        "description": "近 5 日跌幅超 8% 后，今日收阳且放量，急跌后的反弹机会",
        "category": "custom",
        "tags": ["综合", "反转", "抄底"],
        "formula": "PCT(close,5) < -0.08 AND close > open AND volume > MA(volume,20)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 30,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "strong_rebound",
        "name": "强势反弹",
        "name_en": "Strong rebound",
        "description": "RSI 从超卖区回升 + 收盘站上 5 日均线，反弹确认",
        "category": "custom",
        "tags": ["综合", "反弹", "短线"],
        "formula": "RSI(14) > 30 AND RSI(14) < 50 AND close > MA(close,5)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 20,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "volatility_squeeze",
        "name": "波动率收窄（布林带收口）",
        "name_en": "Volatility squeeze",
        "description": "布林带宽度（STD/MA）处于近期低位，即将选择方向",
        "category": "technical",
        "tags": ["波动", "收敛", "突破前兆"],
        "formula": "STD(close,20) / MA(close,20) < 0.02",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 25,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    # ═══════════════════════════════════════════════════════
    # 情绪面（sentiment）
    # ═══════════════════════════════════════════════════════
    {
        "id": "panic_sell",
        "name": "恐慌性抛售",
        "name_en": "Panic selling",
        "description": "单日跌幅超过 7% 且成交量放大 2 倍以上，恐慌情绪释放",
        "category": "sentiment",
        "tags": ["恐慌", "抛售", "极端"],
        "formula": "close < open * 0.93 AND volume > MA(volume,20) * 2",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 25,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "euphoria_buy",
        "name": "狂热追涨",
        "name_en": "Euphoria buying",
        "description": "连续 3 日上涨且成交量持续放大，市场情绪亢奋",
        "category": "sentiment",
        "tags": ["狂热", "追涨", "风险"],
        "formula": "close > open AND DIFF(close,1) > 0 AND volume > MA(volume,20) * 1.5",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 25,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "high_turnover_rate",
        "name": "换手率异常高",
        "name_en": "Abnormally high turnover",
        "description": "当日成交量超过 20 日均量 5 倍，筹码剧烈换手",
        "category": "sentiment",
        "tags": ["换手", "异常", "关注"],
        "formula": "volume > MA(volume,20) * 5",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 25,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "extreme_volatility",
        "name": "极端波动（振幅>10%）",
        "name_en": "Extreme volatility (>10%)",
        "description": "当日最高最低价差超过收盘价 10%，市场分歧极大",
        "category": "sentiment",
        "tags": ["波动", "分歧", "极端"],
        "formula": "(high - low) / close > 0.10",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "sentiment_reversal_bottom",
        "name": "情绪底部反转",
        "name_en": "Sentiment bottom reversal",
        "description": "RSI 极度超卖 + 放量收阳，恐慌情绪后的反转信号",
        "category": "sentiment",
        "tags": ["反转", "底部", "情绪"],
        "formula": "RSI(14) < 25 AND close > open AND volume > MA(volume,20) * 1.5",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 20,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    # ═══════════════════════════════════════════════════════
    # 基本面（fundamental）
    # ═══════════════════════════════════════════════════════
    {
        "id": "fundamental_safe",
        "name": "财务安全（低负债+高流动）",
        "name_en": "Financially safe",
        "description": "资产负债率 < 50% 且流动比率 > 1.5，财务结构健康",
        "category": "fundamental",
        "tags": ["安全", "财务", "稳健"],
        "formula": "debt_asset_ratio < 50 AND current_ratio > 1.5",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "cash_flow_strong",
        "name": "经营现金流充裕",
        "name_en": "Strong operating cash flow",
        "description": "经营现金流/净利润 > 1，盈利质量高",
        "category": "fundamental",
        "tags": ["现金流", "质量", "稳健"],
        "formula": "cfo_to_np > 1",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "high_asset_turnover",
        "name": "资产周转率高效",
        "name_en": "High asset turnover",
        "description": "总资产周转率 > 0.8，资产利用效率高",
        "category": "fundamental",
        "tags": ["运营", "效率", "优质"],
        "formula": "asset_turn_ratio > 0.8",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "quality_growth",
        "name": "优质成长股（ROE+增速双高）",
        "name_en": "Quality growth stock",
        "description": "ROE > 15% 且净利润同比增速 > 20%，兼具盈利能力和成长性",
        "category": "fundamental",
        "tags": ["优质", "成长", "ROE"],
        "formula": "roe > 15 AND yoy_ni > 20",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "low_pe_high_roe",
        "name": "低PE高ROE（巴菲特式）",
        "name_en": "Low PE high ROE (Buffett style)",
        "description": "PE < 20 且 ROE > 18%，巴菲特式价值投资选股",
        "category": "fundamental",
        "tags": ["价值", "巴菲特", "经典"],
        "formula": "pe_ttm < 20 AND roe > 18",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    # ═══════════════════════════════════════════════════════
    # 宏观（macro）- 用个股数据近似反映宏观情绪
    # ═══════════════════════════════════════════════════════
    {
        "id": "market_strong_trend",
        "name": "市场强势（站上所有均线）",
        "name_en": "Market strong trend",
        "description": "价格站上 5/10/20/60 日所有均线，系统性牛市环境",
        "category": "macro",
        "tags": ["宏观", "牛市", "趋势"],
        "formula": "close > MA(close,5) AND close > MA(close,10) AND close > MA(close,20) AND close > MA(close,60)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 65,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "market_weak_trend",
        "name": "市场弱势（跌破所有均线）",
        "name_en": "Market weak trend",
        "description": "价格跌破 5/10/20/60 日所有均线，系统性熊市环境",
        "category": "macro",
        "tags": ["宏观", "熊市", "风控"],
        "formula": "close < MA(close,5) AND close < MA(close,10) AND close < MA(close,20) AND close < MA(close,60)",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 65,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "market_volatility_high",
        "name": "市场高波动期",
        "name_en": "High market volatility",
        "description": "20 日标准差占均价比 > 5%，市场波动加剧",
        "category": "macro",
        "tags": ["宏观", "波动", "风险"],
        "formula": "STD(close,20) / MA(close,20) > 0.05",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 25,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "market_recovery",
        "name": "市场回暖信号",
        "name_en": "Market recovery signal",
        "description": "价格从 60 日低点反弹超 10%，市场底部回暖",
        "category": "macro",
        "tags": ["宏观", "回暖", "底部"],
        "formula": "close > MIN(close,60) * 1.10",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 65,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
    {
        "id": "large_cap_preference",
        "name": "大盘股偏好（市值>500亿）",
        "name_en": "Large cap preference",
        "description": "总市值超过 500 亿，大盘蓝筹股",
        "category": "macro",
        "tags": ["宏观", "大盘", "蓝筹"],
        "formula": "market_cap > 50000000000",
        "formula_type": "dsl",
        "output_type": "boolean",
        "lookback_days": 0,
        "update_frequency": "daily",
        "version": 1,
        "owner": "platform",
        "visibility": "public",
    },
]


def main():
    client = get_supabase_client()

    # 清空已有因子
    ids = [f["id"] for f in FACTORS]
    print(f"🧹 清理已有因子 ({len(ids)} 个)...")
    for fid in ids:
        try:
            client.delete("factor_definitions", filters={"id": f"eq.{fid}"})
        except Exception:
            pass

    # 逐条插入（避免 PostgREST 批量 key 不一致报错）
    print(f"\n📥 插入 {len(FACTORS)} 个因子...")
    success = 0
    for f in FACTORS:
        try:
            client.insert("factor_definitions", [f])
            print(f"  ✅ {f['id']:30} {f['name']}")
            success += 1
        except Exception as e:
            print(f"  ❌ {f['id']:30} {e}")

    print(f"\n🏁 完成！成功 {success}/{len(FACTORS)} 个因子")


if __name__ == "__main__":
    main()
